openapi: 3.0.0
info:
  title: Data Summary API
  version: '1.0'
  description: Web service that stores summaries of user data
  contact:
    name: Tidepool
    url: 'https://www.tidepool.org'
    email: support@tidepool.org
  license:
    name: BSD-2-Clause
    url: 'https://github.com/tidepool-org/clinic/blob/master/LICENSE'
  x-logo:
    url: 'https://github.com/tidepool-org/TidepoolApi/blob/master/assets/images/Tidepool_Logo_Light_Large.png'
    altText: Tidepool Logo
  x-tidepool-service: 'https://github.com/tidepool-org/clinic/'
servers:
  - url: 'http://localhost:8080'
    description: local development
  - url: 'https://dev1.dev.tidepool.org'
    description: dev1
  - url: 'https://qa1.development.tidepool.org'
    description: qa1
  - url: 'https://qa2.development.tidepool.org'
    description: qa2
  - url: 'https://external.integration.tidepool.org'
    description: integration
  - url: 'https://api.tidepool.org'
    description: production
paths:
  '/v1/summaries/{userId}':
    parameters:
      - $ref: '#/components/parameters/userId'
    get:
      summary: Get User Summary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: GetSummary
      description: Retrieve a summary by id
      x-internal: true
      tags:
        - summary
components:
  schemas:
    TidepoolUserId:
      type: string
      title: Tidepool User ID
      pattern: '^([0-9a-f]{10}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$'
      description: 'String representation of a Tidepool User ID. Old style IDs are 10-digit strings consisting of only hexadeximcal digits. New style IDs are 36-digit [UUID v4](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random))'
      readOnly: true
      x-go-type: string
    Summary:
      type: object
      title: summary.v1
      description: ''
      properties:
        lastUpdatedDate:
          type: string
          format: date-time
        firstData:
          type: string
          format: date-time
        lastData:
          type: string
          format: date-time
        lastUploadDate:
          type: string
          format: date-time
        outdatedSince:
          type: string
          format: date-time
        totalDays:
          type: number
          x-go-type: int
        highGlucoseThreshold:
          type: number
          x-go-type: float64
        veryHighGlucoseThreshold:
          type: number
          x-go-type: float64
        lowGlucoseThreshold:
          type: number
          x-go-type: float64
        veryLowGlucoseThreshold:
          type: number
          x-go-type: float64
        periods:
          $ref: '#/components/schemas/SummaryPeriods'
        dailyStats:
          type: array
          items:
            $ref: '#/components/schemas/SummaryStat'
    AverageGlucose:
      title: Blood Glucose (mmol/L)
      description: 'Blood glucose value, in `mmol/L`'
      type: object
      properties:
        units:
          title: Blood Unit (mmol/L)
          type: string
          enum:
            - mmol/L
            - mmol/l
          example: mmol/L
          x-tags:
            - Data
        value:
          title: Blood Value (mmol/L)
          description: A floating point value representing a `mmol/L` value.
          type: number
          format: float
          minimum: 0
          maximum: 55
          example: 5.5
          x-tags:
            - Data
      required:
        - units
        - value
      x-tags:
        - Data
    SummaryStat:
      type: object
      x-stoplight:
        id: rul58weln9wr3
      title: summaryperiod.v1
      description: ''
      properties:
        deviceId:
          type: string
        date:
          type: string
          format: date-time
        lastRecordTime:
          type: string
          format: date-time
        timeInTargetMinutes:
          type: number
          x-go-type: int
        timeInTargetRecords:
          type: number
          x-go-type: int
        timeInHighMinutes:
          type: number
          x-go-type: int
        timeInHighRecords:
          type: number
          x-go-type: int
        timeInVeryHighMinutes:
          type: number
          x-go-type: int
        timeInVeryHighRecords:
          type: number
          x-go-type: int
        timeInLowMinutes:
          type: number
          x-go-type: int
        timeInLowRecords:
          type: number
          x-go-type: int
        timeInVeryLowMinutes:
          type: number
          x-go-type: int
        timeInVeryLowRecords:
          type: number
          x-go-type: int
        totalGlucose:
          type: number
          x-go-type: float64
        timeCGMUseMinutes:
          type: number
          x-go-type: int
        timeCGMUseRecords:
          type: number
          x-go-type: int
    SummaryPeriods:
      type: object
      title: summaryperiods.v1
      description: ''
      properties:
        14d:
          $ref: '#/components/schemas/SummaryPeriod'
    SummaryPeriod:
      type: object
      title: summaryperiod.v1
      description: ''
      properties:
        averageGlucose:
          $ref: '#/components/schemas/AverageGlucose'
        glucoseManagementIndicator:
          type: number
          x-go-type: float64
        timeInTargetPercent:
          type: number
          x-go-type: float64
        timeInTargetMinutes:
          type: number
          x-go-type: int
        timeInTargetRecords:
          type: number
          x-go-type: int
        timeInHighPercent:
          type: number
          x-go-type: float64
        timeInHighMinutes:
          type: number
          x-go-type: int
        timeInHighRecords:
          type: number
          x-go-type: int
        timeInVeryHighPercent:
          type: number
          x-go-type: float64
        timeInVeryHighMinutes:
          type: number
          x-go-type: int
        timeInVeryHighRecords:
          type: number
          x-go-type: int
        timeInLowPercent:
          type: number
          x-go-type: float64
        timeInLowMinutes:
          type: number
          x-go-type: int
        timeInLowRecords:
          type: number
          x-go-type: int
        timeInVeryLowPercent:
          type: number
          x-go-type: float64
        timeInVeryLowMinutes:
          type: number
          x-go-type: int
        timeInVeryLowRecords:
          type: number
          x-go-type: int
        timeCGMUsePercent:
          type: number
          x-go-type: float64
        timeCGMUseMinutes:
          type: number
          x-go-type: int
        timeCGMUseRecords:
          type: number
          x-go-type: int
  securitySchemes:
    sessionToken:
      description: Tidepool Session Token
      type: apiKey
      name: X-Tidepool-Session-Token
      in: header
    serverToken:
      description: Tidepool Server Token
      type: apiKey
      name: X-Tidepool-Session-Token
      in: header
  parameters:
    userId:
      name: userId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/TidepoolUserId'
tags:
  - name: summary
    description: Tidepool Summary Data
security:
  - sessionToken: []
